# Generated by Django 3.1.2 on 2020-11-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('chroma_stft', models.DecimalField(decimal_places=20, max_digits=25)),
                ('rmse', models.DecimalField(decimal_places=20, max_digits=25)),
                ('spectral_centroid', models.DecimalField(decimal_places=20, max_digits=25)),
                ('spectral_bandwidth', models.DecimalField(decimal_places=20, max_digits=25)),
                ('rolloff', models.DecimalField(decimal_places=20, max_digits=25)),
                ('zero_crossing_rate', models.DecimalField(decimal_places=20, max_digits=25)),
                ('tempo', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc1', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc2', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc3', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc4', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc5', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc6', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc7', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc8', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc9', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc10', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc11', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc12', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc13', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc14', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc15', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc16', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc17', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc18', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc19', models.DecimalField(decimal_places=20, max_digits=25)),
                ('mfcc20', models.DecimalField(decimal_places=20, max_digits=25)),
                ('genre', models.CharField(max_length=200)),
            ],
        ),
    ]
